

server:
  port: 8080
  
  
spring:
  application:
    name: department-service

    
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka